/* Generated by Yosys 0.53+11 (git sha1 55bd950af, clang++ 18.1.8 -fPIC -O3) */

module ALU(io_in1, io_in2, io_op, io_out);
  wire [31:0] \$auto$alumacc.cc:431:extract_cmp_alu$29 ;
  wire [31:0] \$auto$alumacc.cc:511:replace_alu$31 ;
  wire [31:0] \$auto$alumacc.cc:511:replace_alu$34 ;
  wire [31:0] \$auto$alumacc.cc:511:replace_alu$41 ;
  wire [31:0] \$auto$alumacc.cc:512:replace_alu$32 ;
  wire [31:0] \$auto$alumacc.cc:512:replace_alu$35 ;
  wire [31:0] \$auto$alumacc.cc:512:replace_alu$42 ;
  wire \$auto$rtlil.cc:2967:Xor$37 ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:18$11_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:19$13_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:20$15_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:21$17_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:22$19_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:23$21_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:24$23_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:25$25_Y ;
  wire \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:26$27_Y ;
  wire [62:0] _GEN_0;
  wire [31:0] _io_out_T_1;
  wire [31:0] _io_out_T_10;
  wire [31:0] _io_out_T_12;
  wire [31:0] _io_out_T_16;
  wire [31:0] _io_out_T_17;
  wire [31:0] _io_out_T_18;
  wire [31:0] _io_out_T_20;
  wire [62:0] _io_out_T_22;
  wire [62:0] _io_out_T_24;
  wire [62:0] _io_out_T_26;
  wire [62:0] _io_out_T_28;
  wire [31:0] _io_out_T_3;
  wire [62:0] _io_out_T_30;
  wire [62:0] _io_out_T_32;
  wire [62:0] _io_out_T_34;
  wire [62:0] _io_out_T_36;
  wire [62:0] _io_out_T_5;
  wire _io_out_T_8;
  wire _io_out_T_9;
  input [31:0] io_in1;
  wire [31:0] io_in1;
  input [31:0] io_in2;
  wire [31:0] io_in2;
  input [3:0] io_op;
  wire [3:0] io_op;
  output [31:0] io_out;
  wire [31:0] io_out;
  assign _io_out_T_18 = io_in1 & io_in2;
  \$alu  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) \$auto$alumacc.cc:495:replace_alu$30  (
    .A(io_in2),
    .B(io_in1),
    .BI(1'h0),
    .CI(1'h0),
    .CO(\$auto$alumacc.cc:512:replace_alu$32 ),
    .X(\$auto$alumacc.cc:511:replace_alu$31 ),
    .Y(_io_out_T_1)
  );
  \$alu  #(
    .A_SIGNED(32'd1),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd1),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) \$auto$alumacc.cc:495:replace_alu$33  (
    .A(io_in1),
    .B(io_in2),
    .BI(1'h1),
    .CI(1'h1),
    .CO(\$auto$alumacc.cc:512:replace_alu$35 ),
    .X(\$auto$alumacc.cc:511:replace_alu$34 ),
    .Y(\$auto$alumacc.cc:431:extract_cmp_alu$29 )
  );
  \$alu  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd32),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd32),
    .Y_WIDTH(32'd32)
  ) \$auto$alumacc.cc:495:replace_alu$40  (
    .A(io_in1),
    .B(io_in2),
    .BI(1'h1),
    .CI(1'h1),
    .CO(\$auto$alumacc.cc:512:replace_alu$42 ),
    .X(\$auto$alumacc.cc:511:replace_alu$41 ),
    .Y(_io_out_T_3)
  );
  assign _io_out_T_8 = \$auto$rtlil.cc:2967:Xor$37  ^ \$auto$alumacc.cc:431:extract_cmp_alu$29 [31];
  assign _io_out_T_9 = ~ \$auto$alumacc.cc:512:replace_alu$42 [31];
  assign \$auto$rtlil.cc:2967:Xor$37  = \$auto$alumacc.cc:512:replace_alu$35 [31] ^ \$auto$alumacc.cc:512:replace_alu$35 [30];
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:18$11_Y  = 4'h1 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:19$13_Y  = 4'h2 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:20$15_Y  = 4'h3 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:21$17_Y  = 4'h4 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:22$19_Y  = 4'h5 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:23$21_Y  = 4'h6 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:24$23_Y  = 4'h7 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:25$25_Y  = 4'h8 == io_op;
  assign \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:26$27_Y  = 4'h9 == io_op;
  assign _io_out_T_17 = io_in1 | io_in2;
  assign _io_out_T_5 = { 31'h00000000, io_in1 } << io_in2[4:0];
  assign _io_out_T_12 = io_in1 >> io_in2[4:0];
  assign _io_out_T_16 = $signed(io_in1) >>> io_in2[4:0];
  assign _io_out_T_20 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:18$11_Y  ? _io_out_T_3 : _io_out_T_1;
  assign _io_out_T_22 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:19$13_Y  ? _io_out_T_5 : { 31'h00000000, _io_out_T_20 };
  assign _io_out_T_24 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:20$15_Y  ? { 62'h0000000000000000, _io_out_T_8 } : _io_out_T_22;
  assign _io_out_T_26 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:21$17_Y  ? { 62'h0000000000000000, _io_out_T_9 } : _io_out_T_24;
  assign _io_out_T_28 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:22$19_Y  ? { 31'h00000000, _io_out_T_10 } : _io_out_T_26;
  assign _io_out_T_30 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:23$21_Y  ? { 31'h00000000, _io_out_T_12 } : _io_out_T_28;
  assign _io_out_T_32 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:24$23_Y  ? { 31'h00000000, _io_out_T_16 } : _io_out_T_30;
  assign _io_out_T_34 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:25$25_Y  ? { 31'h00000000, _io_out_T_17 } : _io_out_T_32;
  assign _io_out_T_36 = \$eq$/home/aotianzhihuo/ysyx-workbench/npc-chisel/generated/ALU.v:26$27_Y  ? { 31'h00000000, _io_out_T_18 } : _io_out_T_34;
  assign _io_out_T_10 = io_in1 ^ io_in2;
  assign _GEN_0 = { 31'h00000000, io_in1 };
  assign io_out = _io_out_T_36[31:0];
endmodule
